# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            dmertl
tagline:          'Development Blog'
description:      'The exciting development adventures of @dmertl'
url:              https://dmertl.github.io

author:
  name:           'David Mertl'
  url:            https://dmertl.com/

paginate:         5
