# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            dmertl
tagline:          'Development Blog'
description:      'The exciting development adventures of @dmertl'
url:              http://dmertl.github.io
baseurl:          /

author:
  name:           'David Mertl'
  url:            http://dmertl.com/

paginate:         5
